<?php

/**
 * @file
 * Contains moduleone.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function moduleone_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the moduleone module.
    case 'help.page.moduleone':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My First Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function moduleone_theme() {
  return [
    'moduleone' => [
      'render element' => 'children',
    ],
  ];
}
